const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
const FETCH_ALL_MOVIE = "FETCH_ALL_MOVIE";
const CREATE_MOVIE = "CREATE_MOVIE";
const EDIT_MOVIE = "EDIT_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

export {
    FETCH_ALL_MOVIES,
    FETCH_ALL_MOVIE,
    CREATE_MOVIE,
    EDIT_MOVIE,
    DELETE_MOVIE,
    AUTHENTICATION,
    LOGOUT
}